networks:
  logicalift:
    driver: bridge

services:
  application:
    build:
      context: ./application/
    volumes:
      - ./application:/var/www/logicalift
    # environment:
    #   - DB_HOST=db
    #   - DB_PORT=5432
    #   - DB_DATABASE=yume_nana
    #   - DB_USERNAME=root
    #   - DB_PASSWORD=password
    # depends_on:
    #   - db
    networks:
      - logicalift
  
  nginx:
    build:
        context: ./nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - application
    networks:
      - logicalift
