networks:
  logicalift:
    driver: bridge

volumes:
  mysql_data:

services:
  application:
    build:
      context: ./application/
    volumes:
      - ./application:/var/www/logicalift
    networks:
      - logicalift
  
  nginx:
    build:
        context: ./nginx
    ports:
      - 8080:80
    volumes:
      - ./application:/var/www/logicalift
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - application
    networks:
      - logicalift
  
  db:
    build: ./db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: logicalift
      MYSQL_USER: logicalift
      MYSQL_PASSWORD: logicalift
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - logicalift
